//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_app_pizza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients_Roles
    {
        public System.Guid IdClient_Roles { get; set; }
        public System.Guid ClientIDClient { get; set; }
        public string RoleName { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
